const desktopReleaseHistory = [
  {
    version: "v1.0.49",
    date: "2026-09-07",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.49",
    zh: [
      "启动时清理旧版 Desktop bridge 残留的依赖声明和包文件；清理失败会记录警告并在下次启动重试，不阻断工作台启动。",
      "修复旧 profile 仅在加载列表登记内置插件时跳过补装的问题，补装改为检查 dependencies 中的安装声明。",
      "兼容 pnpm 11 的 .modules.yaml JSON 状态，离线安装回退到在线安装时保留原 store，避免 ERR_PNPM_UNEXPECTED_STORE。",
      "离线冒烟测试同步校验插件文件、依赖登记和 bundle 激活状态。",
    ],
    en: [
      "Clean legacy Desktop bridge dependency declarations and package files at startup; cleanup warnings retry on the next launch without blocking the workbench.",
      "Fixed upgraded profiles that listed bundled plugins only in the bundle list by checking installation declarations in dependencies before seeding.",
      "Preserved the pnpm 11 store from .modules.yaml when offline installation retries online, preventing ERR_PNPM_UNEXPECTED_STORE.",
      "Offline smoke tests now verify plugin files, dependency declarations, and bundle activation together.",
    ],
  },
  {
    version: "v1.0.48",
    date: "2026-09-07",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.48",
    zh: [
      "Desktop 启动 DSH 时从应用私有目录动态注入桌面桥接；独立 dsh web 使用 Web 插件管理通道，旧版桥接配置会迁移并备份。",
      "更新提示遵循更新库的可用性判断，避免将旧版或暂不可用的版本提示为新版本。",
      "离线资源加入 pnpm 包版本元数据，确保空用户缓存下的首次安装可用，并保留首次安装错误及超时输出供诊断。",
      "新增 Usage Billing 1.0.31、BTW 0.1.3 与 Simplify 0.1.2，内置组件扩充为 13 项。",
      "更新 Codex UI 至 0.2.106、Automation 至 0.1.32、dsh-context 至 0.44.0、MCP Connector 至 0.2.37。",
    ],
    en: [
      "Desktop now injects its bridge from a private application directory, while standalone dsh web uses Web plugin management and migrates legacy bridge configuration with a backup.",
      "Update prompts now respect the updater availability decision, avoiding false offers for older or currently unavailable releases.",
      "Offline resources include pnpm package metadata for first launch with an empty user cache and retain initial install errors and timeout output for diagnosis.",
      "Bundled Usage Billing 1.0.31, BTW 0.1.3, and Simplify 0.1.2, expanding the bundled component catalog to 13 entries.",
      "Updated Codex UI to 0.2.106, Automation to 0.1.32, dsh-context to 0.44.0, and MCP Connector to 0.2.37.",
    ],
  },
  {
    version: "v1.0.47",
    date: "2026-09-06",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.47",
    zh: [
      "将插件安装错误与 DSH 启动分离：安装失败后仍尝试加载工作台。",
      "恢复模式只定位与加载失败相关的插件，并在确认隔离前展示候选列表；无关插件继续启用。",
      "修复非关键插件失败时将可用工作台强制切到恢复页的问题；恢复后的插件需通过完整健康检查才会清除备份。",
      "内置组件更新到 Codex UI 0.2.103、Automation 0.1.31、Skills Manager 0.1.40、Archive Manager 0.1.30、Agency Agents 0.1.32、dsh-context 0.43.0、MCP Connector 0.2.35 与 dshmarket 1.44.0。",
    ],
    en: [
      "Plugin installation errors are now separate from DSH startup, so the desktop still attempts to load the workbench after a failed installation.",
      "Recovery identifies only plugins related to a loading failure and shows candidates before isolation; unrelated plugins remain enabled.",
      "Fixed noncritical plugin errors forcing a usable workbench into recovery; restored plugins must pass a full health check before backups clear.",
      "Updated Codex UI to 0.2.103, Automation to 0.1.31, Skills Manager to 0.1.40, Archive Manager to 0.1.30, Agency Agents to 0.1.32, dsh-context to 0.43.0, MCP Connector to 0.2.35, and dshmarket to 1.44.0.",
    ],
  },
  {
    version: "v1.0.46",
    date: "2026-09-04",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.46",
    zh: [
      "修复 Windows 任务栏未读完成角标：打开已完成任务后会稳定清除未读状态，后续任务列表刷新不再把历史完成任务重复计入。",
    ],
    en: [
      "Fixed the Windows taskbar unread-completion badge so opening completed tasks clears them permanently; later session-list refreshes no longer count historical completed rows again.",
    ],
  },
  {
    version: "v1.0.45",
    date: "2026-09-04",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.45",
    zh: [
      "新增插件恢复模式：启动失败后隔离第三方插件，并提供独立恢复页，支持恢复、卸载或回到最近正常配置。",
      "没有仍需隔离的插件时自动退出恢复模式；恢复会话中的健康启动不再覆盖最近一次已验证的配置检查点。",
      "修复 Windows 关闭关于、设置或快捷键窗口时主窗口闪一下的问题。",
      "将内置插件更新到 Codex UI 0.2.102、IM Connect 0.1.34、Automation 0.1.27、Skills Manager 0.1.38、Archive Manager 0.1.29、Agency Agents 0.1.30、dsh-context 0.41.2、DSH Better Sidebar 0.18.0 和 dshmarket 1.41.0。",
      "稳住运行时解压超时测试：先挂上拒绝断言，再等孙进程 PID，避免 macOS Intel CI 在 200ms 内输掉竞态。本版取代未发布的 v1.0.44 标签。",
    ],
    en: [
      "Added plugin recovery mode: after a failed start the desktop isolates third-party plugins and opens a dedicated page to restore, uninstall, or return to the last healthy configuration.",
      "Recovery now exits automatically when no plugins remain isolated, and a healthy recovery boot no longer overwrites the last verified configuration checkpoint.",
      "Fixed a Windows flash when closing the About, Settings, or Shortcuts windows.",
      "Updated bundled plugins to Codex UI 0.2.102, IM Connect 0.1.34, Automation 0.1.27, Skills Manager 0.1.38, Archive Manager 0.1.29, Agency Agents 0.1.30, dsh-context 0.41.2, DSH Better Sidebar 0.18.0, and dshmarket 1.41.0.",
      "Stabilized the runtime-extraction timeout test so macOS Intel CI no longer races a 200ms deadline before the hanging child writes its PID. This supersedes the unreleased v1.0.44 tag.",
    ],
  },
  {
    version: "v1.0.43",
    date: "2026-09-01",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.43",
    zh: [
      "将内置官方 DSH 运行时及其启动依赖升级到 0.1.2-alpha.3。",
      "将内置生态组件更新到 Codex UI 0.2.97、IM Connect 0.1.30、Archive Manager 0.1.22 和 MCP Connector 0.2.32。",
      "强化离线运行时初始化：Windows 冒烟复用共享插件校验器，鉴权与未鉴权路径都等待桌面就绪标记，并在取消或超时解压时清理完整进程树。",
    ],
    en: [
      "Upgraded the bundled official DSH runtime and its launch peers to 0.1.2-alpha.3.",
      "Updated the bundled ecosystem to Codex UI 0.2.97, IM Connect 0.1.30, Archive Manager 0.1.22, and MCP Connector 0.2.32.",
      "Hardened offline runtime initialization by sharing the bundled-plugin verifier across Windows smoke tests, waiting for the desktop ready marker on both HTTP paths, and cleaning the full extraction process tree when initialization is cancelled or times out.",
    ],
  },
  {
    version: "v1.0.41",
    date: "2026-08-31",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.41",
    zh: [
      "修复离线包缺少官方 DSH 启动所需 peer 依赖的问题，确保随包运行时无需联网即可完整启动。",
      "将便携版首次运行时的校验、解压和大量文件复制移入独立子进程，并展示分阶段进度，避免初始化期间窗口长时间未响应。",
      "将运行时与插件仓库的解压完成标记绑定到随包归档 SHA256；覆盖升级或复用旧便携目录时，空标记和陈旧标记会自动触发重新解压，离线首启不再缺少插件。",
      "将 Windows、macOS 与 Linux 打包冒烟测试统一为强制离线，并在隔离 Profile 中核对全部十个随包插件及其固定版本。",
    ],
    en: [
      "Fixed the offline bundle so it includes every peer required to launch the official DSH runtime without network access.",
      "Moved portable first-run verification, extraction, and bulk file copying into a separate child process with staged progress, preventing the window from becoming unresponsive during initialization.",
      "Bound runtime and plugin-store completion markers to the bundled archive SHA256. Empty or stale markers from overwritten or reused portable directories now trigger re-extraction, so offline first launch no longer starts without plugins.",
      "Made Windows, macOS, and Linux packaged-app smoke tests force offline mode and verify all ten bundled plugins and their pinned versions in an isolated profile.",
    ],
  },
  {
    version: "v1.0.40",
    date: "2026-08-31",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.40",
    zh: [
      "将内置官方 DSH 运行时及其启动依赖升级到 0.1.2-alpha.2，适配启动 Token 鉴权与 alpha.2 所需的原生安装脚本。",
      "将内置生态组件更新到 IM Connect 0.1.27、Skills Manager 0.1.32、Archive Manager 0.1.21、Agency Agents 0.1.23、dsh-context 0.38.5、DSH Better Sidebar 0.18.0-alpha.0、MCP Connector 0.2.31 和 dshmarket 1.38.1。",
      "将 electron-builder 升级到 26.15.7，并刷新供全新安装和缺包自修复使用的离线运行时与插件仓库装配流程。",
      "让 Windows、macOS 与 Linux 打包应用冒烟测试适配 alpha.2 鉴权：在隔离 Profile 中校验预期的未鉴权响应、进程存活、启动诊断以及主窗口创建后的就绪标记。",
    ],
    en: [
      "Upgraded the bundled official DSH runtime and its launch peers to 0.1.2-alpha.2, including authenticated startup-token handling and the alpha.2 native-script requirements.",
      "Updated the bundled ecosystem to IM Connect 0.1.27, Skills Manager 0.1.32, Archive Manager 0.1.21, Agency Agents 0.1.23, dsh-context 0.38.5, DSH Better Sidebar 0.18.0-alpha.0, MCP Connector 0.2.31, and dshmarket 1.38.1.",
      "Upgraded electron-builder to 26.15.7 and refreshed the offline runtime and plugin-store assembly for fresh installs and missing-package repair.",
      "Aligned Windows, macOS, and Linux packaged-app smoke tests with alpha.2 authentication by verifying the expected unauthenticated response, process liveness, startup diagnostics, and the post-window ready marker in isolated profiles.",
    ],
  },
  {
    version: "v1.0.39",
    date: "2026-08-30",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.39",
    zh: [
      "为 Ubuntu、Debian 及其他兼容发行版新增原生 Linux ARM64 / aarch64 安装包，同时提供 .deb 与 .AppImage 制品。",
      "新增 GitHub 托管的原生 ARM64 打包任务与打包应用冒烟测试，不依赖未经验证的交叉编译。",
      "新增经过校验的 Node.js 24.20.0 Linux ARM64 可执行文件哈希，并在发布前检查架构专属的 latest-linux-arm64.yml 更新元数据。",
      "更新中英文下载说明、系统要求与开发文档，使 Linux x64 / ARM64 支持保持一致。",
    ],
    en: [
      "Added native Linux ARM64 / aarch64 packages for Ubuntu, Debian, and other compatible distributions, with both .deb and .AppImage artifacts.",
      "Added a native GitHub-hosted ARM64 packaging job and packaged-app smoke test instead of relying on unverified cross-compilation.",
      "Added the verified Node.js 24.20.0 Linux ARM64 executable checksum and a release guard for the architecture-specific latest-linux-arm64.yml update metadata.",
      "Updated the English and Chinese download, system-requirement, and development documentation for Linux x64 / ARM64 parity.",
    ],
  },
  {
    version: "v1.0.38",
    date: "2026-08-30",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.38",
    zh: [
      "将内置的六个 MichengAI 产品更新到 Codex UI 0.2.94、IM Connect 0.1.26、Automation 0.1.22、Skills Manager 0.1.31、Archive Manager 0.1.19 和 Agency Agents 0.1.22。",
      "将内置生态组件更新到 dsh-context 0.38.3、DSH Better Sidebar 0.17.1、MCP Connector 0.2.29 和 dshmarket 1.38.0。",
      "刷新供全新安装和缺包自修复使用的离线插件目录；已有 Profile 可通过插件市场升级到相同版本，桌面端不会静默覆盖用户主动选择的插件版本。",
      "官方 DSH 运行时继续使用 npm 当前版本 0.1.1-rc.2；仅提供源码的 0.1.2 Alpha 暂不进入桌面稳定通道。",
    ],
    en: [
      "Updated the six bundled MichengAI products to Codex UI 0.2.94, IM Connect 0.1.26, Automation 0.1.22, Skills Manager 0.1.31, Archive Manager 0.1.19, and Agency Agents 0.1.22.",
      "Updated bundled ecosystem components to dsh-context 0.38.3, DSH Better Sidebar 0.17.1, MCP Connector 0.2.29, and dshmarket 1.38.0.",
      "Refreshed the offline plugin catalog used by fresh installs and missing-package repair. Existing profiles can apply the same versions through the plugin market without the desktop silently overriding user-selected package versions.",
      "Kept the official DSH runtime on the current npm release, 0.1.1-rc.2; the source-only 0.1.2 Alpha remains outside the stable desktop channel.",
    ],
  },
  {
    version: "v1.0.37",
    date: "2026-08-27",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.37",
    zh: [
      "让浅色和深色桌面标题栏同步 Codex 风格渐变与当前 DSH 配色，并覆盖设置、键盘快捷键和关于窗口。",
      "原生标题栏菜单关闭后会清除选中状态，点击菜单外部不再留下视觉上的激活样式。",
      "恢复 DSH 视图和桌面设置窗口的 Escape 行为：普通弹层自行处理 Escape，桌面兜底仅关闭可见的设置对话框。",
      "插件市场批量更新会等待整个批次完成后再重启 DSH 运行时，并加入有界超时和安全重载回退。",
    ],
    en: [
      "Synced light and dark desktop title bars with the Codex-style gradient and active DSH color scheme across Settings, Keyboard Shortcuts, and About windows.",
      "Cleared native title-bar menu selection after a dismissed popup so buttons no longer remain visually active.",
      "Restored Escape behavior across the DSH view and desktop settings: ordinary popups handle Escape themselves, while the desktop fallback only closes the visible Settings dialog.",
      "Made marketplace bulk updates wait for the complete batch before recycling the DSH runtime, with a bounded timeout and safe reload fallback.",
    ],
  },
  {
    version: "v1.0.36",
    date: "2026-08-27",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.36",
    zh: [
      "将内置运行时更新到 Node.js 24.20.0 与 pnpm 11.24.0，并校验全部支持平台的可执行文件哈希。",
      "将桌面工具链更新到 Electron 44.0.0、TypeScript 7.0.2、@electron/notarize 3.1.1 与 @types/node 26.4.0。",
      "将 Codex UI 更新到 0.2.89、Automation 更新到 0.1.21、Skills Manager 更新到 0.1.25、Archive Manager 更新到 0.1.16、dsh-context 更新到 0.33.1、MCP Connector 更新到 0.2.24，并将 dshmarket 更新到 1.31.1。",
      "将打包工作流升级到 Checkout、Setup Node、pnpm Setup、Upload Artifact 与 Download Artifact 的当前主版本；其余直接依赖和内置依赖也已核对为最新版。",
    ],
    en: [
      "Updated the bundled runtime to Node.js 24.20.0 and pnpm 11.24.0, including verified executable checksums for every supported platform.",
      "Updated the desktop toolchain to Electron 44.0.0, TypeScript 7.0.2, @electron/notarize 3.1.1, and @types/node 26.4.0.",
      "Updated Codex UI to 0.2.89, Automation to 0.1.21, Skills Manager to 0.1.25, Archive Manager to 0.1.16, dsh-context to 0.33.1, MCP Connector to 0.2.24, and dshmarket to 1.31.1.",
      "Updated the packaging workflow to the current major releases of Checkout, Setup Node, pnpm Setup, Upload Artifact, and Download Artifact; all other direct and bundled dependencies were verified as current.",
    ],
  },
  {
    version: "v1.0.35",
    date: "2026-08-26",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.35",
    zh: [
      "移除设置、键盘快捷键和关于窗口中的 Electron 原生菜单栏，按下 Alt 时不再显示英文 File / Edit / View / Window 菜单。",
    ],
    en: [
      "Removed Electron's native menu bar from Settings, Keyboard Shortcuts, and About windows so pressing Alt can no longer reveal an English File / Edit / View / Window menu.",
    ],
  },
  {
    version: "v1.0.34",
    date: "2026-08-26",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.34",
    zh: [
      "将 dsh-mcp-connector 0.2.21 加入内置离线目录，支持通过 OAuth、API Key、HTTP、stdio 与 JSON 配置管理 MCP 连接。",
      "新增独立更新设置页，提供自动检查并提醒、自动下载后安装前提醒和仅手动检查三种策略。",
      "为打包版本新增延迟且不阻塞启动的更新检查；发现新版本时在后台提醒，安装和重启始终需要用户明确操作。",
      "将 Codex UI 更新到 0.2.88，并刷新兼容的开发依赖。",
      "让社区插件仓库装配方式与 Web Profile 的官方运行时隔离模型保持一致，不再把预发布 DSH peer 重复安装进插件 Profile。",
    ],
    en: [
      "Added dsh-mcp-connector 0.2.21 to the bundled offline catalog for OAuth, API-key, HTTP, stdio, and JSON-based MCP connection management.",
      "Added a dedicated Updates settings page with automatic check-and-notify, automatic download with install confirmation, and manual-only policies.",
      "Added a delayed, non-blocking startup update check for packaged builds. New versions notify in the background, while installation and restart always require explicit user action.",
      "Updated Codex UI to 0.2.88 and refreshed compatible development dependencies.",
      "Aligned community-store assembly with the Web Profile's isolated official-runtime model so prerelease DSH peers are not duplicated into the plugin Profile.",
    ],
  },
  {
    version: "v1.0.33",
    date: "2026-08-26",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.33",
    zh: [
      "新增产品预览截图，同时展示 dsh-context 上下文管理与 DSH Better Sidebar 文件浏览器。",
      "对 Windows 短暂文件占用导致的替换失败增加重试，避免 Profile 更新被临时锁中断。",
    ],
    en: [
      "Added a product preview showing dsh-context management alongside the DSH Better Sidebar file explorer.",
      "Retried transient Windows file replacement failures so Profile updates are not interrupted by short-lived file locks.",
    ],
  },
  {
    version: "v1.0.32",
    date: "2026-08-25",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.32",
    zh: [
      "新增 dsh-context 0.32.0 上下文管理与 dsh-better-sidebar 0.16.1 可扩展工作区侧边栏。",
      "将内置 MichengAI 产品更新到 Codex UI 0.2.87、IM Connect 0.1.24、Automation 0.1.18、Skills Manager 0.1.24、Archive Manager 0.1.14 和 Agency Agents 0.1.21。",
      "将内置插件市场更新到 dshmarket 1.29.2。",
      "扩展首次启动离线插件目录，新旧 Profile 都会通过自修复补种流程获得两个生态插件。",
    ],
    en: [
      "Added dsh-context 0.32.0 for context management and dsh-better-sidebar 0.16.1 for an extensible workspace sidebar.",
      "Updated the bundled MichengAI products to Codex UI 0.2.87, IM Connect 0.1.24, Automation 0.1.18, Skills Manager 0.1.24, Archive Manager 0.1.14, and Agency Agents 0.1.21.",
      "Updated the bundled plugin market to dshmarket 1.29.2.",
      "Extended the offline first-launch catalog so new and existing Profiles receive both ecosystem plugins through the self-healing seed path.",
    ],
  },
  {
    version: "v1.0.31",
    date: "2026-08-25",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.31",
    zh: [
      "新增 Codex 风格任务通知，覆盖任务完成、审批和问题提醒，并提供任务栏标记与通知偏好。",
      "新增原生内联回复，将输入准确发送回产生通知的任务，并支持 Windows Action Center 与冷启动激活。",
      "新增桌面通知身份、紧凑来源图标、带任务名称的标题和国际化操作。",
      "新增独立通知设置页，并分别控制任务完成、审批和问题通知。",
      "整个桌面外壳改为跟随 DeepSeek Harness 内部选择的语言。",
      "修复任务完成通知错误显示任务最早内容而不是最新助手结果的问题。",
    ],
    en: [
      "Added Codex-style task notifications for completed work, approvals, and questions, with taskbar badges and notification preferences.",
      "Added native inline replies that return text to the exact task that produced the notification, including Windows Action Center and cold-start activation.",
      "Added the desktop notification identity, compact source icon, task-aware titles, and localized actions.",
      "Added a dedicated Notifications settings page with independent controls for completion, approval, and question notifications.",
      "Made the entire desktop shell follow the language selected inside DeepSeek Harness.",
      "Fixed completion notifications showing a task's earliest text instead of its latest assistant result.",
    ],
  },
  {
    version: "v1.0.30",
    date: "2026-08-25",
    url: "https://github.com/MichengAI/dsh-codex-desktop/releases/tag/v1.0.30",
    zh: [
      "在未配置 Developer ID 证书时，对 macOS Apple Silicon 与 Intel 完整应用包执行 ad-hoc codesign。",
      "上传安装包前严格验证整个 macOS 应用签名，避免再次发布系统提示应用已损坏的 DMG 或 ZIP。",
      "将安装目录根图标限定为 Windows 专用，避免无关 ICO 文件进入 macOS 应用包并阻断签名。",
      "保留未来 Developer ID 正式签名路径，配置证书后会自动替换 ad-hoc 兜底。",
    ],
    en: [
      "Added ad-hoc codesigning for complete macOS Apple Silicon and Intel app bundles when no Developer ID certificate is configured.",
      "Added strict whole-bundle signature verification before uploading macOS artifacts to prevent damaged-app DMG or ZIP releases.",
      "Scoped the loose installation-directory icon to Windows so an unrelated ICO can no longer block macOS signing.",
      "Preserved the future Developer ID signing path so configured certificates replace the ad-hoc fallback automatically.",
    ],
  },
];

export const recentDesktopReleases = desktopReleaseHistory.slice(0, 5);
